//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class looknorthEntities1 : DbContext
    {
        public looknorthEntities1()
            : base("name=looknorthEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<machine> machines { get; set; }
        public DbSet<oil_usage> oil_usage { get; set; }
        public DbSet<production> productions { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<products_active> products_active { get; set; }
    }
}
