//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class oil_usage
    {
        public int id { get; set; }
        public int m_id { get; set; }
        public Nullable<float> liters { get; set; }
        public System.DateTime recorded { get; set; }
    
        public virtual machine machine { get; set; }
    }
}
